### ISSUE TITLE
Add light avoidance to Monster

### ISSUE THREAD

**Issue by GitAdam** [callumW/HauntedHuntingJam#10]
Investigate possible methods.

**Comment by callumW** [comment]
I think the minimum viable feature here is to make the monster avoid the fire.

It would be nice if the monster could also avoid the flashlight, but it doesn't have to. The reasoning here could be that because the flashlight is electrical, it doesn't affect the monster.

**Comment by callumW** [comment]
I've got an idea of how to make this simpler. We could have a trigger volume around the fires that if the enemy hits them, it gets teleported away/hurt somehow.

**Comment by callumW** [comment]
# Tasks
- [ ] Scale down avoidance/trigger volume with fire
- [ ] Make enemy run right up to player
- [ ] Make enemy avoid fire area

**Comment by callumW** [comment]
haven't got his quite working yet but the enemy gets teleported back to its spawn area and stunned when it enters the fire zone
