### ISSUE TITLE
Harvest Wood

### ISSUE THREAD

**Issue by callumW** [callumW/HauntedHuntingJam#13]
# Description
Need to be able to hit trees and harvest wood from them. For now we just need to track how much wood we have gathered on the player.

## Tasks
- [x] Make Tree ~~Actor~~ USceneComponent
- [x] Research how to get mouse input
- [x] How to detect we are hitting a tree (can we have some sort of volume in front of camera to detect whether a tree is inside
- [x] Display Wood count on screen
- [x] Progressable harvesting (harvest a tree should take a period of time/number of hits)
- [x] Harvesting Sounds

## Pre Pull Request Tasks
- [x] Clean Up Code
