### ISSUE TITLE
The Forest

### ISSUE THREAD

**Issue by callumW** [callumW/HauntedHuntingJam#3]
# Description
The game is going to need a forest for the player to harvest wood from.

Preferably we wouldn't have to manually place all the trees and we could make it infinite (or at least very large!).

It should be optimised in some way so that we aren't loading loads of tree meshes into the game at once. 

However, it should also look like you're in a big forest! 

I think we can do this by loading in some trees around the player and then at a certain radius from the player we have a billboard with overlapping tree images on it! I think this will also give a cool PS1 aesthetic.

# Tasks
- [x] Investigate Methods/Approaches
- [ ] ~~Test out billboard idea~~ (leave for another issue)
- [x] ~~Dynamic Chunk Loading system~~ (Investigated a little, gunna leave it for now)
- [x] No Spawn Areas (i.e. stop tree's from spawning in a certain area
- [x] expose configuration in editor
- [x] can we optimise lighting?
- [x] reattempt optimised tree culling

# Pre-Review Tasks
- [x] Verify Windows Build

**Comment by callumW** [comment]
Obligatory crappy diagram:

![image](https://user-images.githubusercontent.com/5477252/77805128-2017b600-7079-11ea-8b8e-229b5ef62565.jpeg)

**Comment by callumW** [comment]
Adam pointed out that unreal has a [Procedural Foliage Tool](https://docs.unrealengine.com/en-US/Engine/OpenWorldTools/ProceduralFoliage/QuickStart/index.html). Can we leverage this somehow?

**Comment by callumW** [comment]
So taking a quick look at the Procedural Foliage Tool, basically we can give it a set of tree meshes and it will randomly spawn them into an area. We can also place a blocked-off area in which the generator will not spawn any trees! Which is pretty cool.

What I don't know is if we can do all this, and then somehow know whether the player is trying to knock down a tree, and how we manage that.

**Comment by callumW** [comment]
Even if we don't use the Procedural Foliage Tool for trees. we definitely want to use it for getting grass in and stuff.

**Comment by callumW** [comment]
Another consideration is how to efficiently load/unload parts of the world. We could divide the world into blocks and have a spawner for each block, but, would that looks cohesive?

How hard would it be to just go and create a random node generator to generate nodes in space and then spawn tree entities at that point. (I already have experience doing this in my SecretBaseGenerator project).

**Comment by callumW** [comment]
So I've got a very basic tree generation in place and I think it looks pretty cool:

![Screenshot 2020-03-28 at 23 20 18](https://user-images.githubusercontent.com/5477252/77836070-c54e8f00-714a-11ea-9bb3-32e713973491.png)

Basically it just picks some random points in a rect and places trees there (with random rotation). (as of 237260fd4fbb66ff44a2924ea88d26808e9a67b3)

**Comment by callumW** [comment]
Been playing around with the dynamic tree-loading stuff, it actually has a negative affect on performance (likely because I'm evaluating all trees in the scene every loop)

**Comment by callumW** [comment]
I've added in-editor spawning of the trees so I could try out pre-baked lighting but it doesn't quite work as well as I'd hope. It doesn't really improve the performance yet. I'm going to research a bit more about lighting to see if I'm doing something wrong

**Comment by callumW** [comment]
> I've added in-editor spawning of the trees so I could try out pre-baked lighting but it doesn't quite work as well as I'd hope. It doesn't really improve the performance yet. I'm going to research a bit more about lighting to see if I'm doing something wrong

This was because our lights are ```stationary light``` not ```static lights``` and thus can not be baked. However, when I switch to stationary the tree's don't get any shadows (performance is increased).

**Comment by callumW** [comment]
Added generation blocking volumes! 
![Screenshot 2020-03-31 at 22 09 49](https://user-images.githubusercontent.com/5477252/78075547-a5160e80-739c-11ea-80dc-38a6cde4b873.png)

**Comment by callumW** [comment]
In pull request #14
